name: Direct Download with WARP

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
      - name: Start WARP
        run: |
          docker run -d --name warp --cap-add NET_ADMIN -p 1080:1080 caomingjun/warp
          sleep 15
          
      - name: Download APK via WARP
        run: |
          export https_proxy=socks5://127.0.0.1:1080
          export http_proxy=socks5://127.0.0.1:1080
          
          curl -L -o efootball.apk \
            "https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=13803905&key=1397bcc761b71001ca2531910938c18404f645ec&__cf_chl_rt_tk=3pUcL6bDNX3LAxKoMGJ7pGT5AZvVS59FvXr_1Qx1ih4-1778752551-1.0.1.1-YaEeyMrRaH0mZ53uINahp3MxByKTZ_JEBjf9Y1j6hPc"
          
          ls -lh efootball.apk
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: efootball-10.4.2
          path: efootball.apk
          retention-days: 30
          
      - name: Stop WARP
        if: always()
        run: docker stop warp || true
